### ISSUE TITLE
Alta de empresas

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#31]
Cuando se haga click en el botón 

![Image](https://github.com/Xolvex-Projects/growToGo/assets/24461382/65c7353d-dabb-4087-8f73-4746b9c84a18)

Se debera abrir la alta de empresa #7

**Comment by efrenruizrubio** [comment]
Feature finished in fb6ca5705eeea4c6d3b0cd406db5d00ea03c3a15 commit.
