### ISSUE TITLE
Diseño de lista de empresas UX

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#32]
# Resumen
Esta sección nos ayuda a ver como admin de la plataforma todas las empresas registradas en la misma. 

# Diseño

![Image](https://github.com/Xolvex-Projects/growToGo/assets/24461382/cff900a8-c05e-4a5d-8457-1cfd3568d8a2)

# Especificaciones
## Lista empresas
#29 

## Apagar empresa
#30 
## Nueva empresa
#31 
## _onclick_ empresa
#33

**Comment by efrenruizrubio** [comment]
Feature closed by commit 9a8a07763d78e622ac19fb9537a7fbfd3ff1eb97
