### ISSUE TITLE
Editar departamentos feature

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#38]
Este feature es solo visible para el dueño de la empresa o el superadmin de la app cuando se va a una empresa.
Nos ayuda a cambiar la estructura organizacional de la empresa

# Pertenencia del usuario
#83 

# Vista cuando se hace click en editar

![Image](https://github.com/Xolvex-Projects/Symple/assets/24461382/17788dee-d6e3-4f6a-84ca-b495fc1625ae)

**Comment by efrenruizrubio** [comment]
Done
