### ISSUE TITLE
Agregar usuarios - Registro

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#65]
# Resumen
Esta sección es para dar de alta a un usuario a partir de un correo. Deberá tener sus respectivas validaciones y alertas que implican el registro de un usuario nuevo (correo valido, no usuarios repetidos, etc...).

# Diseño
Poner confirmacion de correo

![Image](https://github.com/Xolvex-Projects/growToGo/assets/24461382/e3651bae-6e7f-4cf0-9018-23c0dce6d7fa)

# Especificaciones
## Validaciones
Al querer continuar deberá tener sus respectivas validaciones y alertas en caso de error de:
- Correo valido
- Contraseña válida
- No hay nombre/apellido

## Registrar
Una vez se registra el usuario, se da de alta en los usuarios y ya con esa cuenta pueden ingresar. Se agrega el usuario a la lista del modal que lanzó esto #64

**Comment by efrenruizrubio** [comment]
Closed issue with  commit #69fa9b2
