### ISSUE TITLE
UI departamentos vista normal

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#84]
Como usuario que ve sus departamentos
Debo poder ver una separacion en los departamentos, titulo y linea separadora
Para poder hacer click facilmente y que sea mas agradable a la vista.

# Criterio de aceptacion
## Diseño de card departamento
- Hay un gap de 2 rem
- Una linea abajo de cada departamento/subdepartamento del tamaño de ese contenedor
- Un padding para distinguir departamentos (el que esta funciona bien)
## Titulo
- Un titulo en tamaño decente que diga `Departamentos de [nombre empresa]`
- Alineado con los botones

## Linea separadora
- Una linea separadora entre el titulo y los departamentos
- Color negra y de width .5

## Botones de edicion
Cambiar los botones actuales de edicion y guardar por iconos si se esta en vista de escritorio
### Vista de escritorio
![image](https://github.com/Xolvex-Projects/Symple/assets/24461382/f62690d1-7811-4dd5-b6c0-020ac4d34f26)

- Poner el icono de lapiz para entrar a modo edicion
- Un check y una cruz al estar en el modo edicion
- Alerta confirmadora al querer cerrar sin guardar
### Vista de telefono
Dejar los botones con texto que hay ahorita:
- Editar estructura
     - Guardar estructura
     - Cancelar cambios
# Informacion adicional
![Departamentos empresa](https://github.com/Xolvex-Projects/Symple/assets/24461382/5f72cf9e-e9fd-4e33-9058-6ca9a395180b)
a1-463b-a536-1874984d851e)

**Comment by efrenruizrubio** [comment]
Done
