### ISSUE TITLE
Edicion de departamentos UX

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#85]
Como administrador de empresa editando los departamentos
Debo poder crear/editar y borrar desde la misma pantalla
Para poder ser mas amigable con el usuario.

Migrar lo que ya hay en crear departamentos para que este todo en una sola vista

# Criterio de aceptacion
- Se pueden editar los departamentos
- Poder borrar los departamentos/subdepartamentos
- Al borrar un departamento se borran todos sus subdepartamentos
- Al darle a agregar según 3 tipos de botones:
    - **Agregar departamento**: Este boton esta en grande, al hacer click se agrega un campo seleccionado para que el usuario ponga nuevo departamento
    - **Agregar subdepartamento**: Boton para agregar departamentos hijos de ese departamento. Al hacer click se agrega un campo con esa jerarquia para que el usuario ponga el nombre del subdepartamento. Hay un padding izquierdo para que quede al mismo nivel de los otros
    - **Agregar subdepartamento (subsubdepartamentos)**: Boton para agregar hijos al subdepartamento. Al hacer click se agrega un campo con esa jerarquia para que el usuario ponga el nombre del subdepartamento. Hay un padding izquierdo para que quede al mismo nivel de los otros

## Guardado
- Al hacer click en la palomita se guardan la nueva estructura en esa empresa y se sale del modo edicion
- Al cancelar se vuelve a la estructura anterior y se sale del modo de edicion.

# Informacion adicional
![Departamentos empresa edicion](https://github.com/Xolvex-Projects/Symple/assets/24461382/b0059979-ef95-47de-95b2-8b7ab8fb4d12)

**Comment by efrenruizrubio** [comment]
Siento yo que el botón de Agregar Departamento está de más, preferiría dejar un orden en la edición de departamentos, si quiere añadir un nuevo departamento tiene el botón de la lista que lo lleva al formulario, el cual tiene validaciones. Quedaría pendiente el agregar subdepartamentos, ya que no puedo reutilizar la lógica de mis componentes, como el de Lista y el de Formulario, porque el manejo del estado es totalmente distinto, y no vale la pena refactorizar dichos componentes para un solo caso de uso.

**Comment by mateodelat** [comment]
Ok si se complica mas traer el formulario se queda asi. Lo dejamos solo con la vista para editar nombre y borrarlo. El agregar  nuevos departamentos/subdepartamento se hará desde el botón de agregar departamento.

# Quedaria asi:
![Departamentos empresa edicion](https://github.com/Xolvex-Projects/Symple/assets/24461382/44a6a7ed-1f05-470a-ad3f-ec85c4cf96e6)

**Comment by efrenruizrubio** [comment]
Done
