### ISSUE TITLE
Botones de editar en vista de escritorio

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#86]
Algunos botones de edición no se ven bien al estar en la vista de escritorio

# Criterio de aceptacion
1. Los botones de enviar ocupan todo el espacio en la pantalla en:
     - Agregar departamento
     - Editar empresa
     - Registrar usuario
     - Iniciar sesion

# Recursos
![image](https://github.com/Xolvex-Projects/Symple/assets/24461382/3a38c730-c541-4bee-9616-47d8e3ddd306)
![image](https://github.com/Xolvex-Projects/Symple/assets/24461382/bcf0c2c6-bdc0-46a2-8baf-79e98da8405a)
![image](https://github.com/Xolvex-Projects/Symple/assets/24461382/19620c1e-3b6a-4661-a4f1-0532f5b6bca2)
![image](https://github.com/Xolvex-Projects/Symple/assets/24461382/6e8ccc49-d31d-4149-8c71-e264b2ae6db0)

**Comment by efrenruizrubio** [comment]
Me gustaría saber exactamente qué medidas usar, intenté cambiar las medidas de los botones dependiendo de los distintos breakpoints, pero como no soy diseñador, n o me gustaba el resultado final, por lo que opté a dejarlos con tamaño máximo e ir reduciendo su width total dependiendo del tamaño del dispositivo.

**Comment by mateodelat** [comment]
Si para este van a ser los siguientes tamaños:
- *Registrar usuario nuevo:* 
    - Escritorio: Mismo tamaño que 2 campos (correo y nombre) juntos
    - Movil: Mismo tamaño que 1 campo.

**Comment by efrenruizrubio** [comment]
Done
