### ISSUE TITLE
Flujo usuario no admin

### ISSUE THREAD

**Issue by mateodelat** [Xolvex-Projects/Symple#87]
Cuando como usuario no administrador (puede ser el dueño de la empresa o empleado de la misma) inicio sesion.
Me debe de dirigir a la lista de departamentos de la empresa asociada
Para evitar confundir al usuario viendo el mensaje de no cuentas con empresas asociadas a tu cargo.

# Criterio de aceptacion
- Solo se puede agregar un usuario como administrador de una empresa en toda la plataforma
- Al iniciar sesion con una cuenta me debe dirigir a los departamentos de esa empresa
- Al iniciar sesion como usuario administrador de la plataforma me debe dirigir a admin panel (como esta ahorita)

**Comment by efrenruizrubio** [comment]
Done
